#
# This file is autogenerated by pip-compile with Python 3.11
# by the following command:
#
#    bazel run //third_party/python:requirements.update
#
appdirs==1.4.4 \
    --hash=sha256:7d5d0167b2b1ba821647616af46a749d1c653740dd0d2415100fe26e27afdf41 \
    --hash=sha256:a841dacd6b99318a741b166adb07e19ee71a274450e68237b4650ca1055ab128
    # via
    #   -r third_party/python/requirements.txt
    #   fs
fs==2.4.16 \
    --hash=sha256:660064febbccda264ae0b6bace80a8d1be9e089e0a5eb2427b7d517f9a91545c \
    --hash=sha256:ae97c7d51213f4b70b6a958292530289090de3a7e15841e108fbe144f069d313
    # via
    #   -r third_party/python/requirements.txt
    #   pyfatfs
pyfatfs==1.0.5 \
    --hash=sha256:2376ac3c4d80f9edee170969b665b0ab5e2ec744db0811e1aa50945b59aa0d16 \
    --hash=sha256:e49ea062119fdf6198c7bbbcfe08589d8919e34ac21f5f604d0ed8b5c444972d
    # via -r third_party/python/requirements.txt
six==1.16.0 \
    --hash=sha256:1e61c37477a1626458e36f7b1d82aa5c9b094fa4802892072e49de9c60c4c926 \
    --hash=sha256:8abb2f1d86890a2dfb989f9a77cfcfd3e47c2a354b01111771326f8aa26e0254
    # via
    #   -r third_party/python/requirements.txt
    #   fs

# The following packages are considered to be unsafe in a requirements file:
setuptools==69.1.1 \
    --hash=sha256:02fa291a0471b3a18b2b2481ed902af520c69e8ae0919c13da936542754b4c56 \
    --hash=sha256:5c0806c7d9af348e6dd3777b4f4dbb42c7ad85b190104837488eab9a7c945cf8
    # via fs
